version: "3.8"
services:
  user-service:
    build:
      context: ./user_service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  complaint-service:
    build:
      context: ./complaint-service
    ports:
      - "3002:3002"
    environment:
      DB_URI: mongodb://mongo:27017/complaintdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
