# Menggunakan image node sebagai base image
FROM node:18

# Set working directory
WORKDIR /usr/src/app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy semua file ke working directory
COPY . .

# Expose port
EXPOSE 3003

# Command untuk menjalankan aplikasi
CMD [ "npm", "start" ]
