# Gunakan image dasar Node.js
FROM node:18

# Atur direktori kerja
WORKDIR /usr/src/app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Instal dependensi
RUN npm install

# Salin sisa aplikasi
COPY . .

# Expose port aplikasi
EXPOSE 3001

# Jalankan aplikasi
CMD ["npm", "start"]
